# Generated by Django 4.2.28 on 2026-02-15 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_bookimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookimages',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Image', related_query_name='images', to='Book.listofbooks'),
        ),
    ]
