# Generated by Django 4.2.28 on 2026-02-17 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_alter_bookimages_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookimages',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bookimages',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Book.listofbooks'),
        ),
    ]
