# Generated by Django 4.2.28 on 2026-02-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_alter_bookimages_image_alter_bookimages_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookimages',
            old_name='Image',
            new_name='image',
        ),
        migrations.AddField(
            model_name='listofbooks',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
