# Generated by Django 4.2.28 on 2026-02-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0005_rename_image_bookimages_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomApiPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('view_book', 'owner_only'),),
            },
        ),
    ]
