# Generated by Django 4.2.28 on 2026-02-11 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_customuser_managers_customuser_is_deleter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_deleter',
            new_name='is_deleted',
        ),
    ]
