# Generated by Django 4.2.28 on 2026-02-11 10:18

import User.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_rename_is_deleter_customuser_is_deleted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', User.models.CustomUserManager()),
                ('all_objects', User.models.AllobjectsUser()),
            ],
        ),
    ]
