# Generated by Django 4.2.28 on 2026-02-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='USCitizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('Blue', 'Can drive'), ('Yellow', 'Can vote in elections'), ('Red', 'Can drink alcohol')),
            },
        ),
    ]
