# Generated by Django 4.2.28 on 2026-02-11 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_uscitizen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='USCitizen',
            new_name='CustomPermission',
        ),
    ]
